/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemarh.view;

import com.mycompany.sistemarh.dao.CargoDAO;
import com.mycompany.sistemarh.dao.DepartamentoDAO;
import com.mycompany.sistemarh.dao.FuncionarioDAO;
import com.mycompany.sistemarh.model.Cargo;
import com.mycompany.sistemarh.model.Contato;
import com.mycompany.sistemarh.model.Departamento;
import com.mycompany.sistemarh.model.Endereco;
import com.mycompany.sistemarh.model.Funcionario;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Pichau
 */
public class RegistrarFuncionarios extends javax.swing.JFrame {
    private final Principal principal;
    private final DepartamentoDAO dDAO = new DepartamentoDAO();
    private final CargoDAO cDAO = new CargoDAO();
    private final FuncionarioDAO fDAO = new FuncionarioDAO();

    private List<Endereco> listaEnderecos = new ArrayList<>();
    private List<Contato> listaContatos = new ArrayList<>();

    private boolean modoEdicao = false;
    private int idFuncionario = -1;

    public RegistrarFuncionarios(Principal principal) throws SQLException {
        this.principal = principal;
        initComponents();
        setLocationRelativeTo(this);
        carregarCombos();
        cbxDepFuncionario.addActionListener(evt -> atualizarCargosPorDepartamento());
        atualizarTabelaEndereco();
        atualizarTabelaContato();
    }

    public RegistrarFuncionarios() throws SQLException {
        this(null);
        this.modoEdicao = false;
    }

    // Construtor para edição (usado pela main/Principal)
    public RegistrarFuncionarios(Principal principal, int id) throws SQLException {
        this.principal = principal;
        initComponents();
        setLocationRelativeTo(this);
        carregarCombos();
        cbxDepFuncionario.addActionListener(evt -> atualizarCargosPorDepartamento());
        this.idFuncionario = id;
        carregarFuncionario(id);
        this.modoEdicao = true;
        atualizarTabelaEndereco();
        atualizarTabelaContato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnSalvarFuncionarios = new javax.swing.JButton();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtSalarioFuncionario = new javax.swing.JTextField();
        ftdAdmissaoFuncionario = new javax.swing.JFormattedTextField();
        ftdSaidaFuncionario = new javax.swing.JFormattedTextField();
        btnLimparFuncionarios = new javax.swing.JButton();
        cbCargo = new javax.swing.JComboBox<>();
        cbxDepFuncionario = new javax.swing.JComboBox<>();
        btnCancelarDadosPessoais = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCancelarEnd = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        ftdCep = new javax.swing.JFormattedTextField();
        txtCidade = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        btnLimparEndereco = new javax.swing.JButton();
        btnAdicionarEndereco = new javax.swing.JButton();
        rdbPrincipalEndereco = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnExcluirEndereco = new javax.swing.JButton();
        btnEditarEndereco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEndereco = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnCancelarCtt = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnLimparContato = new javax.swing.JButton();
        rdbPrincipalContato = new javax.swing.JRadioButton();
        btnAdicionarContato = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExcluirContato = new javax.swing.JButton();
        btnEditarContato = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContato = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        btnSalvarFuncionarios.setText("Salvar");
        btnSalvarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFuncionariosActionPerformed(evt);
            }
        });

        txtNomeFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome completo:"));
        txtNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFuncionarioActionPerformed(evt);
            }
        });

        txtSalarioFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Salário"));

        ftdAdmissaoFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Admissão"));
        try {
            ftdAdmissaoFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ftdSaidaFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Saída"));
        try {
            ftdSaidaFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnLimparFuncionarios.setText("Limpar");
        btnLimparFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFuncionariosActionPerformed(evt);
            }
        });

        cbCargo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo:"));

        cbxDepFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Departamento:"));
        cbxDepFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDepFuncionarioActionPerformed(evt);
            }
        });

        btnCancelarDadosPessoais.setText("Cancelar");
        btnCancelarDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDadosPessoaisActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastrar colaborador");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalarioFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ftdSaidaFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                .addComponent(ftdAdmissaoFuncionario, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(141, 141, 141)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxDepFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnSalvarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(btnLimparFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDepFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(ftdAdmissaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(ftdSaidaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimparFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(186, 186, 186)
                .addComponent(btnCancelarDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dados Pessoais", jPanel4);

        btnCancelarEnd.setText("Cancelar");
        btnCancelarEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEndActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        txtRua.setBorder(javax.swing.BorderFactory.createTitledBorder("Rua:"));

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("Número:"));

        txtBairro.setBorder(javax.swing.BorderFactory.createTitledBorder("Bairro:"));

        ftdCep.setBorder(javax.swing.BorderFactory.createTitledBorder("CEP:"));
        try {
            ftdCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtCidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Cidade:"));

        txtEstado.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado:"));

        btnLimparEndereco.setText("Limpar");
        btnLimparEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparEnderecoActionPerformed(evt);
            }
        });

        btnAdicionarEndereco.setText("Adicionar Endereco");
        btnAdicionarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEnderecoActionPerformed(evt);
            }
        });

        rdbPrincipalEndereco.setText("Definir como principal");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cadastrar endereço");

        btnExcluirEndereco.setText("Excluir");
        btnExcluirEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEnderecoActionPerformed(evt);
            }
        });

        btnEditarEndereco.setText("Editar Endereco");
        btnEditarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(txtBairro)
                            .addComponent(txtRua, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCidade)
                            .addComponent(txtEstado)
                            .addComponent(ftdCep, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rdbPrincipalEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(103, 518, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAdicionarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rdbPrincipalEndereco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftdCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        tblEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rua", "Numero", "Bairro", "CEP", "Cidade", "Estado", "Endereço principal?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEndereco);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Endereco", jPanel2);

        btnCancelarCtt.setText("Cancelar");
        btnCancelarCtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCttActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        txtTelefone.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone:"));
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email:"));

        btnLimparContato.setText("Limpar");
        btnLimparContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparContatoActionPerformed(evt);
            }
        });

        rdbPrincipalContato.setText("Definir como principal");

        btnAdicionarContato.setText("Adicionar Contato");
        btnAdicionarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarContatoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cadastrar contato");

        btnExcluirContato.setText("Excluir");
        btnExcluirContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContatoActionPerformed(evt);
            }
        });

        btnEditarContato.setText("Editar Contato");
        btnEditarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdbPrincipalContato, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(448, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnAdicionarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnLimparContato, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirContato, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(rdbPrincipalContato)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparContato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirContato, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        tblContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefone", "Email", "Contato principal?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblContato);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarCtt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarCtt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Contato", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEndActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarEndActionPerformed

    private void btnCancelarCttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCttActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarCttActionPerformed

    private void btnSalvarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFuncionariosActionPerformed
        try {
            Funcionario f = new Funcionario();
            f.setNome(txtNomeFuncionario.getText());
            f.setSalario(Double.parseDouble(txtSalarioFuncionario.getText()));

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            f.setDataEntrada(LocalDate.parse(ftdAdmissaoFuncionario.getText(), dtf));

            String saidaTxt = ftdSaidaFuncionario.getText().replace("/", "").trim();
            if (!saidaTxt.isEmpty()) f.setDataSaida(LocalDate.parse(ftdSaidaFuncionario.getText(), dtf));

            f.setCargo((Cargo) cbCargo.getSelectedItem());
            f.setEnderecos(new ArrayList<>(listaEnderecos));
            f.setContatos(new ArrayList<>(listaContatos));

            if (modoEdicao) {
                f.setId(this.idFuncionario);
                fDAO.atualizar(f); // UPDATE com transação
                JOptionPane.showMessageDialog(this, "Funcionário atualizado com sucesso!");
            } else {
                fDAO.inserir(f); // seu método de insert existente
                JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!");
            }

            if (principal != null) principal.atualizarTabelaFuncionario();
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar funcionário: " + ex.getMessage());
            ex.printStackTrace();
        }   
    }//GEN-LAST:event_btnSalvarFuncionariosActionPerformed

    private void txtNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFuncionarioActionPerformed

    private void btnLimparFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFuncionariosActionPerformed
        txtNomeFuncionario.setText("");
        txtSalarioFuncionario.setText("");
        ftdAdmissaoFuncionario.setText("");
        ftdSaidaFuncionario.setText("");
        cbxDepFuncionario.setSelectedIndex(0);
        cbCargo.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparFuncionariosActionPerformed

    private void cbxDepFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDepFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDepFuncionarioActionPerformed

    private void btnCancelarDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDadosPessoaisActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarDadosPessoaisActionPerformed

    private void btnAdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEnderecoActionPerformed
        Endereco end = new Endereco();
        end.setRua(txtRua.getText());
        end.setNumero(txtNumero.getText());
        end.setBairro(txtBairro.getText());
        end.setCep(ftdCep.getText());
        end.setCidade(txtCidade.getText());
        end.setEstado(txtEstado.getText());
        boolean principal = rdbPrincipalEndereco.isSelected();
        if (principal) {
            for (Endereco e : listaEnderecos) e.setAtivo(false);
            end.setAtivo(true);
        } else {
            end.setAtivo(false);
        }
        listaEnderecos.add(end);
        atualizarTabelaEndereco();
        limparCamposEndereco(); 
    }//GEN-LAST:event_btnAdicionarEnderecoActionPerformed

    private void btnAdicionarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarContatoActionPerformed
        Contato c = new Contato();
        c.setTelefone(txtTelefone.getText());
        c.setEmail(txtEmail.getText());
        boolean principal = rdbPrincipalContato.isSelected();
        if (principal) {
            for (Contato ct : listaContatos) ct.setAtivo(false);
            c.setAtivo(true);
        } else {
            c.setAtivo(false);
        }
        listaContatos.add(c);
        atualizarTabelaContato();
        limparCamposContato();
    }//GEN-LAST:event_btnAdicionarContatoActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void btnLimparEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparEnderecoActionPerformed
        txtRua.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtNumero.setText("");
        ftdCep.setText("");
        rdbPrincipalEndereco.setSelected(false);
    }//GEN-LAST:event_btnLimparEnderecoActionPerformed

    private void btnLimparContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparContatoActionPerformed
        txtTelefone.setText("");
        txtEmail.setText("");
        rdbPrincipalContato.setSelected(false);
    }//GEN-LAST:event_btnLimparContatoActionPerformed

    private void btnExcluirEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEnderecoActionPerformed
        int index = tblEndereco.getSelectedRow();
        if (index >= 0) {
            listaEnderecos.remove(index);  
            atualizarTabelaEndereco();
        }
    }//GEN-LAST:event_btnExcluirEnderecoActionPerformed

    private void btnExcluirContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContatoActionPerformed
        int index = tblContato.getSelectedRow();
        if (index >= 0) {
            listaContatos.remove(index);  
            atualizarTabelaContato();
        }
    }//GEN-LAST:event_btnExcluirContatoActionPerformed

    private void btnEditarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEnderecoActionPerformed
        int index = tblEndereco.getSelectedRow();
        if (index >= 0) {

            // Recupera o endereço selecionado
            Endereco end = listaEnderecos.get(index);

            // Preenche os campos da tela com os dados
            txtRua.setText(end.getRua());
            txtNumero.setText(end.getNumero());
            txtBairro.setText(end.getBairro());
            ftdCep.setText(end.getCep());
            txtCidade.setText(end.getCidade());
            txtEstado.setText(end.getEstado());
            rdbPrincipalEndereco.setSelected(end.isAtivo());

            // Remove temporariamente da lista
            listaEnderecos.remove(index);

            // Atualiza a JTable
            atualizarTabelaEndereco();
        }
    }//GEN-LAST:event_btnEditarEnderecoActionPerformed

    private void btnEditarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContatoActionPerformed
        int index = tblContato.getSelectedRow();
        if (index >= 0) {

            // Recupera contato selecionado
            Contato c = listaContatos.get(index);

            // Preenche campos
            txtTelefone.setText(c.getTelefone());
            txtEmail.setText(c.getEmail());
            rdbPrincipalContato.setSelected(c.isAtivo());

            // Remove temporariamente da lista
            listaContatos.remove(index);

            // Atualiza tabela
            atualizarTabelaContato();
        }
    }//GEN-LAST:event_btnEditarContatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegistrarFuncionarios().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegistrarFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarContato;
    private javax.swing.JButton btnAdicionarEndereco;
    private javax.swing.JButton btnCancelarCtt;
    private javax.swing.JButton btnCancelarDadosPessoais;
    private javax.swing.JButton btnCancelarEnd;
    private javax.swing.JButton btnEditarContato;
    private javax.swing.JButton btnEditarEndereco;
    private javax.swing.JButton btnExcluirContato;
    private javax.swing.JButton btnExcluirEndereco;
    private javax.swing.JButton btnLimparContato;
    private javax.swing.JButton btnLimparEndereco;
    private javax.swing.JButton btnLimparFuncionarios;
    private javax.swing.JButton btnSalvarFuncionarios;
    private javax.swing.JComboBox<Cargo> cbCargo;
    private javax.swing.JComboBox<Departamento> cbxDepFuncionario;
    private javax.swing.JFormattedTextField ftdAdmissaoFuncionario;
    private javax.swing.JFormattedTextField ftdCep;
    private javax.swing.JFormattedTextField ftdSaidaFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdbPrincipalContato;
    private javax.swing.JRadioButton rdbPrincipalEndereco;
    private javax.swing.JTable tblContato;
    private javax.swing.JTable tblEndereco;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSalarioFuncionario;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void carregarCombos() throws SQLException {
        cbxDepFuncionario.removeAllItems();
        cbCargo.removeAllItems();

        cbxDepFuncionario.addItem(new Departamento(0, "Selecione"));
        for (Departamento d : dDAO.listar()) {
            cbxDepFuncionario.addItem(d);
        }

        cbCargo.addItem(new Cargo(0, "Selecione um departamento"));
    }

    private void atualizarCargosPorDepartamento() {
        Departamento d = (Departamento) cbxDepFuncionario.getSelectedItem();
        cbCargo.removeAllItems();
        if (d == null || d.getId() == 0) {
            cbCargo.addItem(new Cargo(0, "Selecione um departamento"));
            return;
        }
        for (Cargo c : cDAO.listarPorDepartamento(d.getId())) cbCargo.addItem(c);
    }

    // ----------------------
    // CARREGAR FUNCIONÁRIO (edição)
    // ----------------------
    private void carregarFuncionario(int id) {
        Funcionario f = fDAO.buscarPorId(id);
        if (f == null) return;

        // preencher campos básicos
        txtNomeFuncionario.setText(f.getNome());
        txtSalarioFuncionario.setText(String.valueOf(f.getSalario()));
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        if (f.getDataEntrada() != null) ftdAdmissaoFuncionario.setText(f.getDataEntrada().format(dtf));
        if (f.getDataSaida() != null) ftdSaidaFuncionario.setText(f.getDataSaida().format(dtf));

        // selecionar departamento/cargo
        Departamento dep = f.getCargo().getDepartamento();
        for (int i = 0; i < cbxDepFuncionario.getItemCount(); i++) {
            Departamento di = cbxDepFuncionario.getItemAt(i);
            if (di.getId() == dep.getId()) {
                cbxDepFuncionario.setSelectedIndex(i);
                break;
            }
        }
        atualizarCargosPorDepartamento();
        for (int i = 0; i < cbCargo.getItemCount(); i++) {
            Cargo ci = cbCargo.getItemAt(i);
            if (ci.getId() == f.getCargo().getId()) {
                cbCargo.setSelectedIndex(i);
                break;
            }
        }

        // listas
        this.listaEnderecos = new ArrayList<>(f.getEnderecos());
        this.listaContatos = new ArrayList<>(f.getContatos());

        // preencher campos do endereço/contato ativo se quiser espelhar
        for (Endereco e : listaEnderecos) {
            if (e.isAtivo()) {
                txtRua.setText(e.getRua());
                txtNumero.setText(e.getNumero());
                txtBairro.setText(e.getBairro());
                ftdCep.setText(e.getCep());
                txtCidade.setText(e.getCidade());
                txtEstado.setText(e.getEstado());
            }
        }
        for (Contato c : listaContatos) {
            if (c.isAtivo()) {
                txtTelefone.setText(c.getTelefone());
                txtEmail.setText(c.getEmail());
            }
        }
    }

    // ----------------------
    // TABELAS
    // ----------------------
    public void atualizarTabelaEndereco() {
        DefaultTableModel tabela = (DefaultTableModel) tblEndereco.getModel();
        tabela.setRowCount(0);
        for (Endereco e : listaEnderecos) {
            tabela.addRow(new Object[]{
                e.getRua(), e.getNumero(), e.getBairro(), e.getCep(), e.getCidade(), e.getEstado(), e.isAtivo() ? "Sim" : "Não"
            });
        }
    }

    public void atualizarTabelaContato() {
        DefaultTableModel tabela = (DefaultTableModel) tblContato.getModel();
        tabela.setRowCount(0);
        for (Contato c : listaContatos) {
            tabela.addRow(new Object[]{
                c.getTelefone(), c.getEmail(), c.isAtivo() ? "Sim" : "Não"
            });
        }
    }


    private void limparCamposEndereco() {
        txtRua.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        ftdCep.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        rdbPrincipalEndereco.setSelected(false);
    }

    private void limparCamposContato() {
        txtTelefone.setText("");
        txtEmail.setText("");
        rdbPrincipalContato.setSelected(false);
    }
}
