/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemarh.view;

import com.mycompany.sistemarh.dao.CargoDAO;
import com.mycompany.sistemarh.dao.DepartamentoDAO;
import com.mycompany.sistemarh.dao.FuncionarioDAO;
import com.mycompany.sistemarh.model.Cargo;
import com.mycompany.sistemarh.model.Contato;
import com.mycompany.sistemarh.model.Departamento;
import com.mycompany.sistemarh.model.Endereco;
import com.mycompany.sistemarh.model.Funcionario;
import com.mycompany.sistemarh.util.ConfiguraComponentes;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Pichau
 */
public class RegistrarFuncionarios extends TelaBase {
    private final Principal principal;
    private final DepartamentoDAO dDAO = new DepartamentoDAO();
    private final CargoDAO cDAO = new CargoDAO();
    private final FuncionarioDAO fDAO = new FuncionarioDAO();

    private List<Endereco> listaEnderecos = new ArrayList<>();
    private List<Contato> listaContatos = new ArrayList<>();

    private boolean modoEdicao = false;
    private int idFuncionario = -1;


    public RegistrarFuncionarios(Principal principal) throws SQLException {
        this.principal = principal;
        initComponents();

        configurarTela16x9(); 
        setResizable(false);
        setLocationRelativeTo(this);
              
        configurarPlaceholders();
        estilizarGeral();
        estilizarCampos();
        estilizarTabelas();

        carregarCombos();
        cbxDepFuncionario.addActionListener(evt -> atualizarCargosPorDepartamento());
        atualizarTabelaEndereco();
        atualizarTabelaContato();
    }

    public RegistrarFuncionarios() throws SQLException {
        this(null);
        this.modoEdicao = false;
    }

    // Construtor para edição (usado pela main/Principal)
    public RegistrarFuncionarios(Principal principal, int id) throws SQLException {
        this.principal = principal;
        initComponents();
        configurarTela16x9();  
        setResizable(false);
        setLocationRelativeTo(this);
        carregarCombos();
        cbxDepFuncionario.addActionListener(evt -> atualizarCargosPorDepartamento());
        this.idFuncionario = id;
        carregarFuncionario(id);
        this.modoEdicao = true;
        atualizarTabelaEndereco();
        atualizarTabelaContato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnSalvarFuncionarios = new javax.swing.JButton();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtSalarioFuncionario = new javax.swing.JTextField();
        ftdAdmissaoFuncionario = new javax.swing.JFormattedTextField();
        ftdSaidaFuncionario = new javax.swing.JFormattedTextField();
        btnLimparFuncionarios = new javax.swing.JButton();
        cbCargo = new javax.swing.JComboBox<>();
        cbxDepFuncionario = new javax.swing.JComboBox<>();
        btnCancelarDadosPessoais = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdadeFuncionario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        ftdCep = new javax.swing.JFormattedTextField();
        txtCidade = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        rdbPrincipalEndereco = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnCancelarEnd = new javax.swing.JButton();
        btnAdicionarEndereco = new javax.swing.JButton();
        btnLimparEndereco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEndereco = new javax.swing.JTable();
        btnEditarEndereco = new javax.swing.JButton();
        btnExcluirEndereco = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rdbPrincipalContato = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnCancelarCtt = new javax.swing.JButton();
        btnAdicionarContato = new javax.swing.JButton();
        btnLimparContato = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContato = new javax.swing.JTable();
        btnEditarContato = new javax.swing.JButton();
        btnExcluirContato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setForeground(new java.awt.Color(60, 63, 65));

        btnSalvarFuncionarios.setText("Salvar");
        btnSalvarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFuncionariosActionPerformed(evt);
            }
        });

        txtNomeFuncionario.setBorder(null);
        txtNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFuncionarioActionPerformed(evt);
            }
        });

        txtSalarioFuncionario.setBorder(null);

        ftdAdmissaoFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Admissão"));
        try {
            ftdAdmissaoFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ftdSaidaFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Saída"));
        try {
            ftdSaidaFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnLimparFuncionarios.setText("Limpar");
        btnLimparFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFuncionariosActionPerformed(evt);
            }
        });

        cbCargo.setBorder(null);

        cbxDepFuncionario.setBorder(null);
        cbxDepFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDepFuncionarioActionPerformed(evt);
            }
        });

        btnCancelarDadosPessoais.setText("Cancelar");
        btnCancelarDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDadosPessoaisActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRAR DADOS PESSOAIS");

        txtIdadeFuncionario.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxDepFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftdSaidaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftdAdmissaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnSalvarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnCancelarDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxDepFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addComponent(ftdAdmissaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftdSaidaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(txtSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dados Pessoais", jPanel4);

        txtRua.setBorder(null);

        txtNumero.setBorder(null);

        txtBairro.setBorder(null);

        ftdCep.setBorder(javax.swing.BorderFactory.createTitledBorder("CEP:"));
        try {
            ftdCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtCidade.setBorder(null);

        txtEstado.setBorder(null);

        rdbPrincipalEndereco.setText("Definir como principal");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("CADASTRAR ENDEREÇO");

        btnCancelarEnd.setText("Cancelar");
        btnCancelarEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEndActionPerformed(evt);
            }
        });

        btnAdicionarEndereco.setText("Adicionar Endereco");
        btnAdicionarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEnderecoActionPerformed(evt);
            }
        });

        btnLimparEndereco.setText("Limpar");
        btnLimparEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                            .addComponent(txtEstado))
                                        .addGap(26, 26, 26)
                                        .addComponent(rdbPrincipalEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ftdCep, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnAdicionarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 605, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnCancelarEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdbPrincipalEndereco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftdCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tblEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rua", "Numero", "Bairro", "CEP", "Cidade", "Estado", "Endereço principal?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEndereco);

        btnEditarEndereco.setText("Editar Endereco");
        btnEditarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEnderecoActionPerformed(evt);
            }
        });

        btnExcluirEndereco.setText("Excluir");
        btnExcluirEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarEndereco)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Endereco", jPanel2);

        txtTelefone.setBorder(null);
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        txtEmail.setBorder(null);

        rdbPrincipalContato.setText("Definir como principal");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("CADASTRAR CONTATO");

        btnCancelarCtt.setText("Cancelar");
        btnCancelarCtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCttActionPerformed(evt);
            }
        });

        btnAdicionarContato.setText("Adicionar Contato");
        btnAdicionarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarContatoActionPerformed(evt);
            }
        });

        btnLimparContato.setText("Limpar");
        btnLimparContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparContatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(rdbPrincipalContato, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnAdicionarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparContato, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(819, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarCtt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnCancelarCtt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdbPrincipalContato)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparContato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefone", "Email", "Contato principal?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblContato);

        btnEditarContato.setText("Editar Contato");
        btnEditarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContatoActionPerformed(evt);
            }
        });

        btnExcluirContato.setText("Excluir");
        btnExcluirContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnExcluirContato, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirContato, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Contato", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEndActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarEndActionPerformed

    private void btnCancelarCttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCttActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarCttActionPerformed

    private void btnSalvarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFuncionariosActionPerformed
        try {
            // --- nome ---
            String nome = txtNomeFuncionario.getText().trim();
            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(this, "O nome não pode estar vazio.");
                return;
            }

            // --- idade ---
            String idadeTxt = txtIdadeFuncionario.getText().trim();
            if (idadeTxt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe a idade.");
                return;
            }

            int idade;
            try {
                idade = Integer.parseInt(idadeTxt);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Idade inválida. Informe um número inteiro.");
                return;
            }

            if (idade < 18 || idade > 75) {
                JOptionPane.showMessageDialog(this,
                    "A idade deve ser entre 18 e 75 anos.",
                    "Idade inválida",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // --- data de admissão (usa método que já valida formato) ---
            LocalDate dataAdmissao;
            try {
                dataAdmissao = obterDataAdmissao(); // lança Exception com mensagem amigável se inválida
                validarDataAdmissao(dataAdmissao, idade); // valida regras de negócio
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Validação", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // --- salário ---
            String salarioTxt = txtSalarioFuncionario.getText().trim();
            if (salarioTxt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o salário.");
                return;
            }

            double salario;
            try {
                // aceita vírgula ou ponto como separador decimal
                salario = Double.parseDouble(salarioTxt.replace(",", "."));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Salário inválido. Use apenas números (ex: 3500.00).");
                return;
            }
            if (salario < 0) {
                JOptionPane.showMessageDialog(this, "Salário não pode ser negativo.");
                return;
            }

            // --- data de saída (opcional) ---
            LocalDate dataSaida = null;
            String saidaTxt = ftdSaidaFuncionario.getText().replace("/", "").trim();
            if (!saidaTxt.isEmpty()) {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                try {
                    dataSaida = LocalDate.parse(ftdSaidaFuncionario.getText(), dtf);
                } catch (DateTimeParseException e) {
                    JOptionPane.showMessageDialog(this, "Data de saída inválida. Use dd/MM/yyyy.");
                    return;
                }
                // valida coerência: saída >= admissão
                if (dataSaida.isBefore(dataAdmissao)) {
                    JOptionPane.showMessageDialog(this, "A data de saída não pode ser anterior à data de admissão.");
                    return;
                }
            }

            // --- cargo ---
            if (cbCargo.getSelectedItem() == null || ((Cargo) cbCargo.getSelectedItem()).getId() == 0) {
                JOptionPane.showMessageDialog(this, "Selecione um cargo válido.");
                return;
            }
            Cargo cargo = (Cargo) cbCargo.getSelectedItem();

            // --- montar objeto Funcionario ---
            Funcionario f = new Funcionario();
            f.setNome(nome);
            f.setIdade(idade);
            f.setSalario(salario);
            f.setDataEntrada(dataAdmissao);
            if (dataSaida != null) f.setDataSaida(dataSaida);
            f.setCargo(cargo);
            f.setEnderecos(new ArrayList<>(listaEnderecos));
            f.setContatos(new ArrayList<>(listaContatos));

            // --- inserir ou atualizar ---
            if (modoEdicao) {
                f.setId(this.idFuncionario);
                fDAO.atualizar(f);
                JOptionPane.showMessageDialog(this, "Funcionário atualizado com sucesso!");
            } else {
                fDAO.inserir(f);
                JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!");
            }

            if (principal != null) {
                principal.atualizarTabelaFuncionario();
            }

            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar funcionário (BD): " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar funcionário: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarFuncionariosActionPerformed

    private void txtNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFuncionarioActionPerformed

    private void btnLimparFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFuncionariosActionPerformed
        txtNomeFuncionario.setText("");
        txtIdadeFuncionario.setText("");
        txtSalarioFuncionario.setText("");
        ftdAdmissaoFuncionario.setText("");
        ftdSaidaFuncionario.setText("");
        cbxDepFuncionario.setSelectedIndex(0);
        cbCargo.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparFuncionariosActionPerformed

    private void cbxDepFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDepFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDepFuncionarioActionPerformed

    private void btnCancelarDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDadosPessoaisActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarDadosPessoaisActionPerformed

    private void btnAdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEnderecoActionPerformed
        Endereco end = new Endereco();

        String rua = txtRua.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();

        if (rua == null || rua.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "A rua não pode estar vazia.",
                "Validação",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (cidade == null || cidade.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "A cidade não pode estar vazia.",
                "Validação",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (estado == null || estado.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "O estado não pode estar vazio.",
                "Validação",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        end.setRua(rua.trim());
        end.setNumero(txtNumero.getText().trim());
        end.setBairro(txtBairro.getText().trim());
        end.setCep(ftdCep.getText().trim());
        end.setCidade(cidade.trim());
        end.setEstado(estado.trim());

        boolean principal = rdbPrincipalEndereco.isSelected();

        if (principal) {
            for (Endereco e : listaEnderecos) {
                e.setAtivo(false);
            }
            end.setAtivo(true);
        } else {
            end.setAtivo(false);
        }

        listaEnderecos.add(end);
        atualizarTabelaEndereco();
        limparCamposEndereco();
    }//GEN-LAST:event_btnAdicionarEnderecoActionPerformed

    private void btnAdicionarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarContatoActionPerformed
        Contato c = new Contato();

        // ===== VALIDAÇÕES =====
        String telefone = txtTelefone.getText();
        String email = txtEmail.getText();

        if (telefone == null || telefone.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "O telefone é obrigatório.",
                "Validação",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (email == null || email.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "O e-mail é obrigatório.",
                "Validação",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // validação simples de formato de e-mail
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(
                this,
                "Informe um e-mail válido.",
                "Validação",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // ===== POPULA O OBJETO =====
        c.setTelefone(telefone.trim());
        c.setEmail(email.trim());

        // ===== CONTATO PRINCIPAL =====
        boolean principal = rdbPrincipalContato.isSelected();

        if (principal) {
            for (Contato ct : listaContatos) {
                ct.setAtivo(false);
            }
            c.setAtivo(true);
        } else {
            c.setAtivo(false);
        }

        // ===== ADICIONA NA LISTA =====
        listaContatos.add(c);
        atualizarTabelaContato();
        limparCamposContato();

    }//GEN-LAST:event_btnAdicionarContatoActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void btnLimparEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparEnderecoActionPerformed
        txtRua.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtNumero.setText("");
        ftdCep.setText("");
        rdbPrincipalEndereco.setSelected(false);
    }//GEN-LAST:event_btnLimparEnderecoActionPerformed

    private void btnLimparContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparContatoActionPerformed
        txtTelefone.setText("");
        txtEmail.setText("");
        rdbPrincipalContato.setSelected(false);
    }//GEN-LAST:event_btnLimparContatoActionPerformed

    private void btnExcluirEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEnderecoActionPerformed
        int index = tblEndereco.getSelectedRow();
        if (index >= 0) {
            listaEnderecos.remove(index);  
            atualizarTabelaEndereco();
        }
    }//GEN-LAST:event_btnExcluirEnderecoActionPerformed

    private void btnExcluirContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContatoActionPerformed
        int index = tblContato.getSelectedRow();
        if (index >= 0) {
            listaContatos.remove(index);  
            atualizarTabelaContato();
        }
    }//GEN-LAST:event_btnExcluirContatoActionPerformed

    private void btnEditarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEnderecoActionPerformed
        int index = tblEndereco.getSelectedRow();
        if (index >= 0) {

            // Recupera o endereço selecionado
            Endereco end = listaEnderecos.get(index);

            // Preenche os campos da tela com os dados
            txtRua.setText(end.getRua());
            txtNumero.setText(end.getNumero());
            txtBairro.setText(end.getBairro());
            ftdCep.setText(end.getCep());
            txtCidade.setText(end.getCidade());
            txtEstado.setText(end.getEstado());
            rdbPrincipalEndereco.setSelected(end.isAtivo());

            // Remove temporariamente da lista
            listaEnderecos.remove(index);

            // Atualiza a JTable
            atualizarTabelaEndereco();
        }
    }//GEN-LAST:event_btnEditarEnderecoActionPerformed

    private void btnEditarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContatoActionPerformed
        int index = tblContato.getSelectedRow();
        if (index >= 0) {

            // Recupera contato selecionado
            Contato c = listaContatos.get(index);

            // Preenche campos
            txtTelefone.setText(c.getTelefone());
            txtEmail.setText(c.getEmail());
            rdbPrincipalContato.setSelected(c.isAtivo());

            // Remove temporariamente da lista
            listaContatos.remove(index);

            // Atualiza tabela
            atualizarTabelaContato();
        }
    }//GEN-LAST:event_btnEditarContatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegistrarFuncionarios().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegistrarFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarContato;
    private javax.swing.JButton btnAdicionarEndereco;
    private javax.swing.JButton btnCancelarCtt;
    private javax.swing.JButton btnCancelarDadosPessoais;
    private javax.swing.JButton btnCancelarEnd;
    private javax.swing.JButton btnEditarContato;
    private javax.swing.JButton btnEditarEndereco;
    private javax.swing.JButton btnExcluirContato;
    private javax.swing.JButton btnExcluirEndereco;
    private javax.swing.JButton btnLimparContato;
    private javax.swing.JButton btnLimparEndereco;
    private javax.swing.JButton btnLimparFuncionarios;
    private javax.swing.JButton btnSalvarFuncionarios;
    private javax.swing.JComboBox<Cargo> cbCargo;
    private javax.swing.JComboBox<Departamento> cbxDepFuncionario;
    private javax.swing.JFormattedTextField ftdAdmissaoFuncionario;
    private javax.swing.JFormattedTextField ftdCep;
    private javax.swing.JFormattedTextField ftdSaidaFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdbPrincipalContato;
    private javax.swing.JRadioButton rdbPrincipalEndereco;
    private javax.swing.JTable tblContato;
    private javax.swing.JTable tblEndereco;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdadeFuncionario;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSalarioFuncionario;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void carregarCombos() throws SQLException {
        cbxDepFuncionario.removeAllItems();
        cbCargo.removeAllItems();

        cbxDepFuncionario.addItem(new Departamento(0, "Selecione"));
        for (Departamento d : dDAO.listar()) {
            cbxDepFuncionario.addItem(d);
        }

        cbCargo.addItem(new Cargo(0, "Selecione um cargo"));
    }

    private void atualizarCargosPorDepartamento() {
        Departamento d = (Departamento) cbxDepFuncionario.getSelectedItem();
        cbCargo.removeAllItems();
        if (d == null || d.getId() == 0) {
            cbCargo.addItem(new Cargo(0, "Selecione um cargo"));
            return;
        }
        for (Cargo c : cDAO.listarPorDepartamento(d.getId())) cbCargo.addItem(c);
    }

    private void carregarFuncionario(int id) {
        Funcionario f = fDAO.buscarPorId(id);
        if (f == null) return;

        // preencher campos básicos
        txtNomeFuncionario.setText(f.getNome());
        txtIdadeFuncionario.setText(String.valueOf(f.getIdade()));
        txtSalarioFuncionario.setText(String.valueOf(f.getSalario()));
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        if (f.getDataEntrada() != null) ftdAdmissaoFuncionario.setText(f.getDataEntrada().format(dtf));
        if (f.getDataSaida() != null) ftdSaidaFuncionario.setText(f.getDataSaida().format(dtf));

        // selecionar departamento/cargo
        Departamento dep = f.getCargo().getDepartamento();
        for (int i = 0; i < cbxDepFuncionario.getItemCount(); i++) {
            Departamento di = cbxDepFuncionario.getItemAt(i);
            if (di.getId() == dep.getId()) {
                cbxDepFuncionario.setSelectedIndex(i);
                break;
            }
        }
        atualizarCargosPorDepartamento();
        for (int i = 0; i < cbCargo.getItemCount(); i++) {
            Cargo ci = cbCargo.getItemAt(i);
            if (ci.getId() == f.getCargo().getId()) {
                cbCargo.setSelectedIndex(i);
                break;
            }
        }

        // listas
        this.listaEnderecos = new ArrayList<>(f.getEnderecos());
        this.listaContatos = new ArrayList<>(f.getContatos());

        // preencher campos do endereço/contato ativo se quiser espelhar
        for (Endereco e : listaEnderecos) {
            if (e.isAtivo()) {
                txtRua.setText(e.getRua());
                txtNumero.setText(e.getNumero());
                txtBairro.setText(e.getBairro());
                ftdCep.setText(e.getCep());
                txtCidade.setText(e.getCidade());
                txtEstado.setText(e.getEstado());
            }
        }
        for (Contato c : listaContatos) {
            if (c.isAtivo()) {
                txtTelefone.setText(c.getTelefone());
                txtEmail.setText(c.getEmail());
            }
        }
    }

    // ----------------------
    // TABELAS
    // ----------------------
    public void atualizarTabelaEndereco() {
        DefaultTableModel tabela = (DefaultTableModel) tblEndereco.getModel();
        tabela.setRowCount(0);
        for (Endereco e : listaEnderecos) {
            tabela.addRow(new Object[]{
                e.getRua(), e.getNumero(), e.getBairro(), e.getCep(), e.getCidade(), e.getEstado(), e.isAtivo() ? "Sim" : "Não"
            });
        }
    }

    public void atualizarTabelaContato() {
        DefaultTableModel tabela = (DefaultTableModel) tblContato.getModel();
        tabela.setRowCount(0);
        for (Contato c : listaContatos) {
            tabela.addRow(new Object[]{
                c.getTelefone(), c.getEmail(), c.isAtivo() ? "Sim" : "Não"
            });
        }
    }


    private void limparCamposEndereco() {
        txtRua.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        ftdCep.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        rdbPrincipalEndereco.setSelected(false);
    }

    private void limparCamposContato() {
        txtTelefone.setText("");
        txtEmail.setText("");
        rdbPrincipalContato.setSelected(false);
    }
    
    private LocalDate obterDataAdmissao() throws Exception {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String textoData = ftdAdmissaoFuncionario.getText().trim();

        // caso esteja usando JFormattedTextField com máscara, verifique se está preenchido
        if (textoData.isEmpty() || textoData.equals("//")) {
            throw new Exception("Informe a data de admissão.");
        }

        try {
            return LocalDate.parse(textoData, formatter);
        } catch (DateTimeParseException e) {
            throw new Exception("Data de admissão inválida. Use o formato dd/MM/yyyy.");
        }
    }

    private void validarDataAdmissao(LocalDate dataAdmissao, int idade) throws Exception {
        LocalDate hoje = LocalDate.now();

        // não pode ser no futuro
        if (dataAdmissao.isAfter(hoje)) {
            throw new Exception("A data de admissão não pode ser no futuro.");
        }

        // data mínima aceitável considerando a idade informada (nasceu, no máximo, há 'idade' anos)
        LocalDate dataMinima = hoje.minusYears(idade);

        if (dataAdmissao.isBefore(dataMinima)) {
            throw new Exception("A data de admissão é incompatível com a idade informada.");
        }

        // regra extra: não aceitar anos muito antigos (opcional)
        if (dataAdmissao.getYear() < 1900) {
            throw new Exception("A data de admissão é muito antiga.");
        }
    }

    private void estilizarGeral() {

        // Fundo geral
 

        // Títulos
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28));
        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28));
        jLabel3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28));

        // Botões padrão (sem rounded, sem inventar moda)
        javax.swing.JButton[] botoes = {
            btnSalvarFuncionarios, btnLimparFuncionarios,
            btnCancelarDadosPessoais, btnAdicionarEndereco,
            btnEditarEndereco, btnExcluirEndereco, btnLimparEndereco,
            btnAdicionarContato, btnEditarContato, btnExcluirContato,
            btnLimparContato, btnCancelarEnd, btnCancelarCtt
        };

        for (var btn : botoes) {
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
            btn.setFocusPainted(false);
        }
    }

    private void estilizarCampos() {

        javax.swing.JTextField[] campos = {
            txtNomeFuncionario, txtIdadeFuncionario, txtSalarioFuncionario,
            txtRua, txtNumero, txtBairro, txtCidade, txtEstado,
            txtTelefone, txtEmail
        };

        for (var c : campos) {
            c.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        }

        ftdAdmissaoFuncionario.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        ftdSaidaFuncionario.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        ftdCep.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        cbxDepFuncionario.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        cbCargo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    }

    private void estilizarTabelas() {

        estilizarTabela(tblEndereco);
        estilizarTabela(tblContato);
    }

    private void estilizarTabela(javax.swing.JTable tabela) {

        tabela.setRowHeight(32);
        tabela.setShowGrid(false);
        tabela.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tabela.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        tabela.getTableHeader().setReorderingAllowed(false);

        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);


        javax.swing.table.DefaultTableCellRenderer centro = new javax.swing.table.DefaultTableCellRenderer();
        centro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        for (int i = 0; i < tabela.getColumnCount(); i++) {
            tabela.getColumnModel().getColumn(i).setCellRenderer(centro);
        }
    }

    private void configurarPlaceholders() {
        ConfiguraComponentes ui = new ConfiguraComponentes();

        ui.configCampoTexto(txtNomeFuncionario, " Nome completo");
        ui.configCampoTexto(txtIdadeFuncionario, " Idade");
        ui.configCampoTexto(txtSalarioFuncionario, " Salário");

        ui.configCampoTexto(txtRua, " Rua");
        ui.configCampoTexto(txtNumero, " Número");
        ui.configCampoTexto(txtBairro, " Bairro");
        ui.configCampoTexto(txtCidade, " Cidade");
        ui.configCampoTexto(txtEstado, " Estado");

        ui.configCampoTexto(txtTelefone, " Telefone");
        ui.configCampoTexto(txtEmail, " E-mail");
    }

    
}
